# -*- coding: utf-8 -*-
"""detectDefect.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFD71ksnp-loQiGARFDUufAITqXf4rFr
"""

!pip install opencv-python numpy matplotlib

from google.colab import files
uploaded = files.upload()

import cv2
import matplotlib.pyplot as plt

img = cv2.imread('semDefectImageSample.png')
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.imshow(img_rgb)
plt.title("Original Image")
plt.axis('off')

gray = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2GRAY)

plt.imshow(gray, cmap='gray')
plt.title("Grayscale Image")
plt.axis('off')

blur = cv2.GaussianBlur(gray, (5,5), 0)

plt.imshow(blur, cmap='gray')
plt.title("Blurred Image")
plt.axis('off')

_, binary = cv2.threshold(
    blur, 0, 255,
    cv2.THRESH_BINARY + cv2.THRESH_OTSU
)

plt.imshow(binary, cmap='gray')
plt.title("Binary Image")
plt.axis('off')

kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7,7))
opened = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel)

final = cv2.morphologyEx(opened, cv2.MORPH_CLOSE, kernel)

plt.imshow(final, cmap='gray')
plt.title("Final Defect Mask")
plt.axis('off')

cv2.imwrite('defect_mask.png', final)
files.download('defect_mask.png')

import cv2
import numpy as np

img = cv2.imread('semDefectImageSample.png')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
blur = cv2.GaussianBlur(gray, (5,5), 0)

_, binary = cv2.threshold(
    blur, 0, 255,
    cv2.THRESH_BINARY + cv2.THRESH_OTSU
)

kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7,7))
opened = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel)
final = cv2.morphologyEx(opened, cv2.MORPH_CLOSE, kernel)

cv2.imwrite('defect_mask.png', final)

2025CTZ8808/
│── report.pdf
└── src/
    └── detectDefect.py